/* Auto-generated by code-line-tracker/upload.py — do not edit manually */
window.CODE_STATS = {
  lines7d: 5730,
  updatedAt: '2026-04-14',
  byDay: [{ date: '2026-04-09', lines: 176 }, { date: '2026-04-10', lines: 3040 }, { date: '2026-04-11', lines: 314 }, { date: '2026-04-13', lines: 1809 }, { date: '2026-04-14', lines: 391 }]
};
