/* Auto-generated by code-line-tracker/upload.py — do not edit manually */
window.CODE_STATS = {
  lines7d: 8361,
  updatedAt: '2026-06-10',
  byDay: [{ date: '2026-06-04', lines: 2962 }, { date: '2026-06-05', lines: 3024 }, { date: '2026-06-06', lines: 420 }, { date: '2026-06-09', lines: 1708 }, { date: '2026-06-10', lines: 247 }]
};
