/* ============================================================
   RESONANT LABS — Site Data
   ============================================================

   This is the only file you need to edit for content changes:
     • Add or update a GitHub / live URL for an app
     • Change a release date or description
     • Add a new app or blog post

   After saving, upload only this file to go live.
   ============================================================ */

window.SITE_DATA = {

  /* ----------------------------------------------------------
     APPS
     ----------------------------------------------------------
     To update an existing app (e.g. add a GitHub URL):
       Find the app block below and fill in the value.

     To add a new app:
       Copy one of the blocks below, paste it at the top of
       the list, and fill in all the fields.
  ---------------------------------------------------------- */
  apps: [
    {
      id: 'consentkit',
      name: 'ConsentKit',
      shortDesc: 'Free, open-source GDPR cookie consent widget. Drop one JS file into any site — full consent management, Google Consent Mode v2, four categories. No subscription.',
      tags: ['Developer Tool', 'Open Source'],
      emoji: '🍪',
      status: 'live',
      image: 'Media/Consentkit.png',
      gradientFrom: '#10b981',
      gradientTo: '#06b6d4',
      githubUrl: 'https://github.com/sokiicz/consentkit',
      liveUrl: 'https://github.com/sokiicz/consentkit',
      liveLabel: 'Download',
      detailUrl: 'apps/consentkit.html',
      releaseDate: '6 Mar 2026',
      updates: [
        { date: '2026-03-06', note: 'Initial release — FTP static version, GCM v2, shadow DOM isolation', label: 'v1.0' },
        { date: '2026-03-21', note: 'Mobile draggable reopener with drag-to-dismiss gesture; auto-hides when all cookies are accepted', label: 'v1.1' },
      ],
    },
    {
      id: 'music-mouse',
      name: 'Music Mouse',
      shortDesc: 'An interactive musical canvas inspired by Laurie Spiegel\'s 1986 classic. Move your mouse — make music. No keyboard, no notes, no rules.',
      tags: ['Music', 'Web App', 'Open Source'],
      emoji: '🎵',
      status: 'live',
      image: 'Media/Music-mouse.png',
      gradientFrom: '#8b5cf6',
      gradientTo: '#22d3ee',
      githubUrl: 'https://github.com/sokiicz/music-mouse',
      liveUrl: 'https://sokiicz.github.io/Music-Mouse/',
      liveLabel: 'Open App',
      detailUrl: 'apps/music-mouse.html',
      releaseDate: '3 Mar 2026',
      updates: [
        { date: '2026-03-03', note: 'Initial release — interactive canvas, Web Audio API, Laurie Spiegel-inspired', label: 'v1 released' },
      ],
    },
    {
      id: 'otocsvet',
      name: 'OtočSvět',
      shortDesc: 'A multiplayer map puzzle — rotate tiles to reconstruct real-world city maps. Solo play, daily challenge, and a leaderboard. Built on OpenStreetMap and MapTiler.',
      tags: ['Game', 'Maps', 'Puzzle', 'OSM'],
      emoji: '🌍',
      status: 'live',
      image: null,
      gradientFrom: '#1e3a5f',
      gradientTo: '#6366f1',
      githubUrl: null,
      liveUrl: 'https://frontend-sokiiczs-projects.vercel.app',
      liveLabel: 'Play Beta',
      detailUrl: null,
      releaseDate: '2026-04-22',
      updates: [
        { date: '2026-04-17', note: 'Project started — pnpm monorepo, Fastify + Prisma + PostgreSQL backend, MapTiler puzzle generator, React 19 frontend', label: 'Scaffold' },
        { date: '2026-04-21', note: 'Scoring system, admin puzzle review panel, daily challenge, session resume on reload, Czech city name generator, leaderboard by grid size, zoom/skip controls, loading screen, city labels on puzzles', label: 'Core gameplay' },
        { date: '2026-04-22', note: 'GitHub Actions deploy to Vercel, admin rate limiting, timer drift fixes', label: 'Deploy' },
      ],
    },
    {
      id: 'qr-clock',
      name: 'QR Clock',
      shortDesc: 'An intentionally inconvenient clock. The time is hidden inside a QR code that updates every second. Scan to find out what time it is.',
      tags: ['Tool', 'Fun', 'Minimal'],
      emoji: '⬛',
      status: 'live',
      image: null,
      gradientFrom: '#0d0d0d',
      gradientTo: '#1a1a2e',
      githubUrl: 'https://github.com/sokiicz/qr-clock',
      liveUrl: 'https://sokiicz.github.io/qr-clock/',
      liveLabel: 'Open Clock',
      detailUrl: 'apps/qr-clock.html',
      releaseDate: '2026-03-17',
      updates: [
        { date: '2026-03-17', note: 'Initial release — fullscreen QR clock with quotes, jokes, facts, multi-part stories, secret codes, easter eggs, and optional Google Sheets CSV source.', label: 'v1.0' },
      ],
    },
    {
      id: 'vagoshit',
      name: 'VagoshIt',
      shortDesc: 'Collaborative group activity planner — vote on ideas, share availability, and actually get things done together.',
      tags: ['Social', 'Planning', 'Groups', 'Next.js', 'Supabase'],
      emoji: '🗓️',
      status: 'live',
      image: 'Media/Vagoshit.png',
      gradientFrom: '#6366f1',
      gradientTo: '#8b5cf6',
      githubUrl: 'https://github.com/sokiicz/vagoshit',
      liveUrl: 'https://vagoshit.com',
      liveLabel: 'Open App',
      detailUrl: 'apps/vagoshit.html',
      releaseDate: '2026-03-13',
      updates: [
        { date: '2026-03-13', note: 'Initial scaffold — Next.js 15 + Supabase. Auth, groups, activities, voting, availability grid, calendar, friends, notifications. Build passing.', label: 'Scaffold' },
        { date: '2026-03-15', note: 'Launched live at vagoshit.com. Added avatar upload, recurring events, saved places, group channels with archiving, friend system with invite links, user profile pages, activity co-organizers, \'Plan again\' duplicate feature, \'Happening now\' banners.', label: 'Live' },
        { date: '2026-03-19', note: 'Major UI overhaul: tabless group layout, context nav, dashboard redesign. Group slugs and personalised URLs. Birthday tracking in group calendar and members tab. Event share links with rich OG preview images. Unified notifications feed. Security hardening, rate limiting, GDPR data export.', label: 'UI overhaul' },
        { date: '2026-03-25', note: 'Birthday detail pages with auto-created group chat channels 7 days before each birthday.', label: 'Birthday channels' },
        { date: '2026-04-10', note: 'Web Push notifications (VAPID + service worker) with per-type toggles. \'The Game\' mini-game — admin-triggered group challenge sent to all members. Multi-day events with end date. Chat emoji reactions with double-tap heart, quick bar, and popup picker.', label: 'Push + mini-game' },
        { date: '2026-04-17', note: 'Group notepads with topic folders. Emoji reactions on notes. Dreams folder. Beztak RSVP type. Event list filters.', label: 'Notepads + reactions' },
        { date: '2026-04-20', note: 'The Game frequency setting (one-off vs. recurring). Cross-device read sync for notepads. Save confirmation in mini-game settings.', label: 'The Game v2' },
      ],
    },
    {
      id: 'shithead',
      name: 'Shithead',
      shortDesc: 'Real-time multiplayer card game — last player holding cards loses. Play with friends or bots, chat, drag-sort your hand, and enjoy the idle poop animation while you wait. No accounts needed.',
      tags: ['Game', 'Multiplayer', 'Cards', 'Real-time'],
      emoji: '💩',
      status: 'live',
      image: null,
      gradientFrom: '#1a4a2e',
      gradientTo: '#2d6a46',
      githubUrl: null,
      liveUrl: 'https://shithead-3d6b3.web.app/',
      liveLabel: 'Play',
      detailUrl: null,
      releaseDate: '2026-03-11',
      updates: [
        { date: '2026-03-10', note: 'Initial build: full game engine, bot opponents, in-game chat, sound reactions', label: 'v0.1' },
        { date: '2026-03-11', note: 'Lobby chat, ready badges, drag-and-drop hand ordering, turn/game timers, quick-play, discard pile visual, idle poop animation + fart sound, mute/surrender, 24h game expiry, phase-3 chain mechanic, rules fixes', label: 'v1.0 Live' },
      ],
    },
    {
      id: 'spekplatz',
      name: 'SpekPlatz',
      shortDesc: 'A community map for discovering and sharing hidden spots — rooftops, viewpoints, parks, beaches, and more. Find places worth remembering.',
      tags: ['Maps', 'Web App', 'Open Source'],
      emoji: '📍',
      status: 'live',
      image: 'Media/Spekplatz.png',
      gradientFrom: '#10b981',
      gradientTo: '#3b82f6',
      githubUrl: 'https://github.com/sokiicz/SpekPlatz',
      liveUrl: 'https://spekplatz.app',
      liveLabel: 'Open App',
      detailUrl: 'apps/spekplatz.html',
      releaseDate: '20 Feb 2026',
      updates: [
        { date: '2026-02-20', note: 'Initial release — community map, spot submission, Firebase backend', label: 'v1 released' },
      ],
    },
    {
      id: 'rps-battle',
      name: 'RPS Battle',
      shortDesc: 'Real-time multiplayer Rock Paper Scissors battle game with virtual coins. No real money — a reminder that the thrill of betting never needs to cost you anything.',
      tags: ['Game', 'Multiplayer', 'Real-time', 'WebSockets'],
      emoji: '⚔️',
      status: 'live',
      image: 'Media/RPS-Battle.png',
      gradientFrom: '#6366f1',
      gradientTo: '#f43f5e',
      githubUrl: null,
      liveUrl: 'https://rps-battle-5486e.web.app',
      liveLabel: 'Play Now',
      detailUrl: 'apps/rps-battle.html',
      releaseDate: '12 Mar 2026',
      updates: [
        { date: '2026-03-11', note: 'Initial development — full-stack multiplayer game with auth, betting, real-time battles', label: 'v0.1' },
        { date: '2026-03-12', note: 'Polished and ready for deployment. Source kept private — built to demonstrate fun betting without real money. Gambling is harmful; this game is a safe alternative.', label: 'v1.0' },
      ],
    },
    {
      id: 'daylog',
      name: 'DayLog',
      shortDesc: 'A personal daily life tracker — log habits, metrics, events and moods. Joy Index tracks what percentage of your days include something genuinely fun. No accounts, no cloud, everything on your device.',
      tags: ['Productivity', 'Web App', 'Open Source'],
      emoji: '◉',
      status: 'live',
      image: 'Media/DayLog.png',
      gradientFrom: '#6366f1',
      gradientTo: '#a855f7',
      githubUrl: 'https://github.com/sokiicz/daylog',
      liveUrl: 'https://sokiicz.github.io/daylog/',
      liveLabel: 'Open App',
      detailUrl: 'apps/daylog.html',
      releaseDate: '10 Mar 2026',
      updates: [
        { date: '2026-03-09', note: 'Development started — React 19 + Vite + IndexedDB, routing in place', label: 'Started development' },
        { date: '2026-03-10', note: 'v2 released — habits, metrics, events, mood tracking, Joy Index, stats, export/import', label: 'v2 released' },
      ],
    },
    {
      id: 'resonant-labs',
      name: 'Resonant Labs',
      shortDesc: 'This very website — a full portfolio site with dark space theme, animated background, tag filtering, cookie consent, comments, and newsletter. Built entirely with Claude Code.',
      tags: ['Web App', 'Open Source'],
      emoji: '🌊',
      status: 'live',
      image: 'Media/ResonantLabs.png',
      gradientFrom: '#8b5cf6',
      gradientTo: '#22d3ee',
      githubUrl: 'https://github.com/sokiicz/resonant-labs',
      liveUrl: 'https://resonantlabs.online',
      liveLabel: 'Home',
      detailUrl: 'apps/resonant-labs.html',
      releaseDate: '1 Mar 2026',
      updates: [
        { date: '2026-03-01', note: 'Initial launch — dark space theme, app gallery, blog, newsletter', label: 'Site launched' },
        { date: '2026-03-06', note: 'ConsentKit integrated, screenshots added, WIP tracker added', label: 'New features added' },
        { date: '2026-03-10', note: 'Activity ticker, app changelogs, dedicated apps page added', label: 'New features added' },
        { date: '2026-03-18', note: 'SEO: robots.txt, sitemap, canonical and OG tags sitewide. Mobile fixes: hamburger menu, hero gap, draggable cookie widget. Blog posts rewritten with personal voice.', label: 'SEO + mobile' },
        { date: '2026-03-23', note: 'Code lines stats ticker, released-this-month counter. Organization schema for search results. App detail pages expanded.', label: 'Stats + SEO' },
      ],
    },
    {
      id: 'ylaway',
      name: 'Ylaway',
      shortDesc: 'Coordinate care for your pets and plants while away. Share trusted helpers, assign days, and get simple reassuring updates.',
      tags: ['Pets', 'Coordination', 'Family'],
      emoji: '🐾',
      status: 'wip',
      image: null,
      gradientFrom: '#a8edca',
      gradientTo: '#4fbdba',
      githubUrl: null,
      liveUrl: null,
      liveLabel: 'Open App',
      detailUrl: null,
      releaseDate: null,
      updates: [
        { date: '2026-03-23', note: 'Project started. Scaffold created.' },
      ],
    },
    {
      id: 'growbox',
      name: 'Growbox Controller',
      shortDesc: 'Fully automated indoor growbox for one habanero pepper plant. Raspberry Pi + ESP32, MQTT, Telegram bot, AI plant vision.',
      tags: ['IoT', 'Python', 'ESP32', 'Raspberry Pi', 'Automation'],
      emoji: '🌱',
      status: 'wip',
      image: null,
      gradientFrom: '#14532d',
      gradientTo: '#166534',
      githubUrl: null,
      liveUrl: null,
      liveLabel: 'Open Dashboard',
      detailUrl: null,
      releaseDate: null,
      updates: [
        { date: '2026-03-20', note: 'Initial build — full system scaffolded: ESP32 firmware, Pi automation modules, Flask dashboard, Telegram bot, AI vision, wiring guide, setup docs.', label: 'Initial build' },
      ],
    },
    {
      id: 'wildround',
      name: 'Wildround',
      shortDesc: 'Real-time multiplayer party game. Complete wild tasks, earn points, outlast your friends.',
      tags: ['Game', 'Party', 'Real-time', 'Multiplayer'],
      emoji: '🎲',
      status: 'wip',
      image: null,
      gradientFrom: '#7c3aed',
      gradientTo: '#4f46e5',
      githubUrl: null,
      liveUrl: null,
      liveLabel: 'Play now',
      detailUrl: null,
      releaseDate: null,
      updates: [
        { date: '2026-03-14', note: 'Initial scaffold: lobby, QR join, real-time tasks, scoreboard', label: 'MVP scaffold' },
      ],
    },
    {
      id: 'timeinvoice',
      name: 'TimeInvoice',
      shortDesc: 'Self-hosted time tracking and invoicing for freelancers. Log hours, manage clients and projects, generate PDF invoices with QR payment codes. Supports CZK, EUR and SEPA.',
      tags: ['Productivity', 'Web App', 'Open Source'],
      emoji: '⏱',
      status: 'wip',
      image: null,
      gradientFrom: '#0ea5e9',
      gradientTo: '#2563eb',
      githubUrl: null,
      liveUrl: null,
      liveLabel: 'Open App',
      detailUrl: null,
      releaseDate: null,
      updates: [
        { date: '2026-03-09', note: 'Core invoicing working — PDF generation, QR payment codes (SPAYD + EPC), 29 tests passing', label: 'Development started' },
      ],
    },
  ],

  /* ----------------------------------------------------------
     BLOG POSTS
     ----------------------------------------------------------
     To add a new post:
       Copy one of the blocks below, paste it at the top,
       and fill in the fields. Make sure the url points to
       the actual blog post file you created.
  ---------------------------------------------------------- */
  posts: [
    {
      id: 'bitcoin-100k',
      title: 'I Built a Website So I\'d Stop Checking CoinMarketCap',
      excerpt: 'Bitcoin was approaching $100K and I kept refreshing CMC for one number. So I built a page that only answers that one question. Here\'s the story and where it\'s going.',
      date: '18 Mar 2026',
      readTime: '4 min read',
      tag: 'Crypto',
      tagClass: 'badge-amber',
      gradientFrom: '#f59e0b',
      gradientTo: '#f97316',
      url: 'blog/bitcoin-100k.html',
    },
    {
      id: 'art-of-prompting',
      title: 'The Art of Prompting: How I Actually Work',
      excerpt: 'After 12 apps built with Claude Code, here\'s the honest truth: the workflow builds itself. You don\'t study prompting. You just start building.',
      date: '22 Feb 2026',
      readTime: '7 min read',

      // Tag label and style. Styles: badge-primary (purple), badge-amber, badge-cyan
      tag: 'Process',
      tagClass: 'badge-amber',

      // Card gradient colours
      gradientFrom: '#f59e0b',
      gradientTo:   '#ef4444',

      // Path to the blog post file
      url: 'blog/art-of-prompting.html',
    },
    {
      id: 'why-ai-not-code',
      title: 'Why I\'m Building Apps with AI Instead of Learning to Code',
      excerpt: 'I tried Hello World as a kid and hated it. Then CSS, then Google Ads scripts, then every AI tool that promised to bridge the gap. Most couldn\'t. Then one did.',
      date: '15 Feb 2026',
      readTime: '9 min read',
      tag: 'Thoughts',
      tagClass: 'badge-primary',
      gradientFrom: '#8b5cf6',
      gradientTo:   '#22d3ee',
      url: 'blog/why-ai-not-code.html',
    },
    {
      id: 'open-source-and-ai',
      title: 'Open Source and AI: A New Model for Sharing Software',
      excerpt: 'If an AI wrote every line, should I charge for it? The answer felt obvious — give it all away, and let ideas multiply.',
      date: '28 Jan 2026',
      readTime: '4 min read',
      tag: 'Philosophy',
      tagClass: 'badge-cyan',
      gradientFrom: '#10b981',
      gradientTo:   '#3b82f6',
      url: 'blog/open-source-and-ai.html',
    },
  ],

};
